backend:
  name: github
  repo: lassediercks/allers-artists

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "artists"
    label: "Artists"
    identifier_field: name
    folder: "artists"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Profilbild", name: "profileimage", widget: "image" }
      - { label: "Beschreibung", name: "description", widget: "string" }
      - {
          label: "Bilder",
          name: "pictures",
          widget: "list",
          field: { label: Bild, name: "picture", widget: "image" },
        }
      - label: Tags
        name: hashtags
        widget: list
        fields:
          - label: "Hashtags"
            name: "tag"
            widget: "relation"
            collection: "tags"
            searchFields: ["name"]
            valueField: "name"
            displayFields: ["name"]
      - label: Steckbrief
        name: bio
        widget: "list"
        fields:
          - { label: "Beschreibung", name: "description", widget: "string" }
          - { label: "Inhalt", name: "content", widget: "string" }
      - label: Vita
        name: vita
        widget: "list"
        fields:
          - { label: "Jahr", name: "year", widget: "string" }
          - { label: "Beschreibung", name: "description", widget: "string" }
      - label: Repertoire
        name: repertoire
        widget: "list"
        fields:
          - { label: "Jahr", name: "year", widget: "string" }
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Beschreibung", name: "description", widget: "string" }
      - label: Videos
        name: videos
        widget: "list"
        fields:
          - label: "Beschreibung"
            name: "description"
            widget: "string"
          - label: "Datei"
            name: "file"
            widget: "file"
            media_library:
              config:
                multiple: true
  - name: "tags"
    label: "Hashtags"
    identifier_field: name
    folder: "hashtags"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
