backend:
  name: github
  repo: lassediercks/allers-artists

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "artists"
    label: "Artists"
    identifier_field: name
    folder: "artists"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Profilbild", name: "profileimage", widget: "image" }
      - { label: "Beschreibung", name: "description", widget: "string" }
      - {
          label: "Bilder",
          name: "pictures",
          widget: "list",
          field: { label: Bild, name: "picture", widget: "image" },
        }
      - label: Vita
        name: vita
        widget: "list"
        fields:
          - label: "Eintrag"
            name: "entry"
            widget: "object"
            fields:
              - { label: "Jahr", name: "year", widget: "string" }
              - { label: "Beschreibung", name: "description", widget: "string" }
      - label: Steckbrief
        name: bio
        widget: "list"
        fields:
          - label: "Eintrag"
            name: "entry"
            widget: "object"
            fields:
              - { label: "Beschreibung", name: "description", widget: "string" }
              - { label: "Inhalt", name: "content", widget: "string" }
      - label: Ausbildung
        name: education
        widget: "list"
        fields:
          - label: "Eintrag"
            name: "entry"
            widget: "object"
            fields:
              - { label: "Jahr", name: "year", widget: "string" }
              - { label: "Inhalt", name: "content", widget: "string" }
      - label: Theater
        name: theater
        widget: "list"
        fields:
          - label: "Eintrag"
            name: "entry"
            widget: "object"
            fields:
              - { label: "Jahr", name: "year", widget: "string" }
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Beschreibung", name: "description", widget: "string" }
