backend:
  name: github
  repo: lassediercks/allers-artists

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "artists"
    label: "artists"
    folder: "artists"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Beschreibung", name: "description", widget: "string" }
      - { label: "Bild", name: "picture", widget: "Image" }
